name: Python Pipe

on: push

jobs:
  test:
    runs-on:
    steps:
      - uses: actions/checkout@v2
      - run: python hello.py
   build:
     needs: [test]
     runs-on:
     steps:
       - uses: actions/checkout@v2
       - uses: actions/upload-artifact@v2
         with:
           name: hello
           path: .
  
